### PR TITLE
add landing message #1

### PR DESCRIPTION
**Pull request by AJisHere88**

### CODE REVIEW

**Review by Ham159 — COMMENTED** [review]
Aj you did a great job but how about if we can do the <h1> to <H1>.

**Comment by AJisHere88** [comment]
Understood, I will do that.

**Comment by Ham159** [comment]
I saw you did the changes which looks fine I believe you have ran the commands in Bash also.
________________________________

**Comment by Ham159** [comment]
I have created a new issue in github please let me know if you have any question. we can knock this out today.
________________________________

**Review by AJisHere88 — COMMENTED** [review]
I understand what you would like me to change, I will do that.

**Pull request merged**
